# Generated by Django 4.0.6 on 2022-09-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='ti=his is a test', max_length=1000),
            preserve_default=False,
        ),
    ]
