# Generated by Django 4.0.6 on 2022-09-16 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orderitem_ordered_orderitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
